[cosmic-ray]
module-path = "app"
python-version = ""
timeout = 10.0
excluded-modules = []
test-command = "nosetests -v test"

[cosmic-ray.cloning]
method = 'copy'
commands = []

[cosmic-ray.execution-engine]
name = "local"
